version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: tasklist
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
